Presentation/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Presentation.Controllers;

[Authorize]
public class DashboardController : Controller
{
    [Route("admin/[controller]")]
    public IActionResult Index()
    {
        return View();
    }
}

Presentation/Controllers/MembersController.cs
using Authentication.Contexts;
using Authentication.Models;
using Business.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Presentation.Models;

namespace Presentation.Controllers;

[Authorize]
public class MembersController : Controller
{
    private readonly IUserService _userService;
    private readonly AuthenticationContext _context;

    public MembersController(IUserService userService, AuthenticationContext authenticationContext)
    {
        _userService = userService;
        _context = authenticationContext;
    }

    [Route("admin/[controller]")]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddMember()
    {
        
        return View();
    }


    [HttpGet]
    public async Task<JsonResult> SearchUsers(string term)
    {
        if(string.IsNullOrWhiteSpace(term))
        {
            return Json(new List<object>());
        }

        var users = await _context.Users
            .Include(u => u.Profile)
            .Where(u => u.Profile!.FirstName!.Contains(term) || u.Profile.LastName!.Contains(term) || u.Email!.Contains(term))
            .Select(u => new {u.Id, u.Profile!.ImageUrl, FullName = $"{u.Profile.FirstName} {u.Profile.LastName}"})
            .ToListAsync();

        return Json(users);
    }
}

Presentation/Views/Shared/Partials/_LogoType.cshtml
<a href="@Url.Content("~/")" class="logotype">
    <img src="~/Images/Logo/alpha-logotype-icon.svg" alt="Alpha Portal" />
    <span>alpha</span>
</a>

Presentation/Views/Shared/Partials/_NavLinksSideBar.cshtml
<div class="nav-links">
    <a class="nav-link @(Context.Request.Path == "/" || Context.Request.Path == "/admin/dashboard" ? "active" : "")" asp-controller="Dashboard" asp-action="Index">
        <i class="bi bi-border-style"></i>
        <span>Dashboard</span>    
    </a>

    <a class="nav-link @(Context.Request.Path == "/admin/projects" ? "active" : "")" asp-controller="Projects" asp-action="Index">
        <i class="bi bi-briefcase-fill"></i>
        <span>Projects</span>
    </a>

    <a class="nav-link @(Context.Request.Path == "/admin/members" ? "active" : "")" asp-controller="Members" asp-action="Index">
        <i class="fa-duotone fa-solid fa-user-group"></i>
        <span>Members</span>
    </a>

    <a class="nav-link @(Context.Request.Path == "/admin/clients" ? "active" : "")" asp-controller="Clients" asp-action="Index">
        <i class="fa-solid fa-handshake"></i>
        <span>Clients</span>
    </a>
</div>

Presentation/Views/Shared/Partials/_NotificationsMenu.cshtml
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
    var roleName = User.FindFirstValue(ClaimTypes.Role) ?? "";
    var notificationResult = await notificationService.GetNotificationASync(userId, roleName);
    var notifications = notificationResult.Result;
}

<div class="notifications-menu-container">

    <div id="notificationsIcon" data-type="dropdown" data-target="#notificationsDropdown" class="notifications-icon">

        @if (notifications!.Any())
        {
            <div class="notifications-symbol">
                <div class="outer-circle">
                    <div class="inner-red-circle"></div>
                </div>
            </div>
        }

        <i class="bi bi-bell-fill"></i>
        </div>
    </div>

<div id="notificationsDropdown" class="notifications-dropdown-container">

    <header class="menu-header">
        <h1 class="h3">Notifications</h1>
        <div class="notifications-red-circle">
            <span class="notification-number">@notifications!.Count()</span>
        </div>
    </header>


     @if (notifications != null)
    {
        
        <div class="notifications">
            @foreach (var notification in notifications)
            {
                <div class="notification-item-container" data-id="@notification.Id">
                    <img class="image" src="@notification.Image" />
                    <div class="message">@notification.Message</div>
                    <div class="time" data-created="@notification.CreateDate.ToString("s")">@notification.CreateDate</div>
                    <button class="btn btn-close" onclick="dismissNotification('@notification.Id')"></button>
            </div>
            }
         </div>
        
    } 
</div>

<script>
    function removeNotification(notificationId) {
        const element = document.querySelector(`.notification-item-container[data-id="${notificationId}"]`);
        if (element) {
            element.remove();
            updateNotificationCount();
        }
    }

     async function dismissNotification(notificationId) {

            try {

                const res = await fetch(`/api/notifications/dismiss/${notificationId}`, { method: 'POST' })
                if (res.ok) {
                    removeNotification(notificationId)
                }
                else {
                    console.error('Error removing notification')
                }
            }
            catch (error) {
                console.error('Error removing notification: ', error)
            }
        }

        function updateNotificationCount() {
        const notifications = document.querySelector('.notifications');
        const notificationNumber = document.querySelector('.notification-number');
        const notificationDropdownButton = document.getElementById('notificationsIcon');
        const count = notifications.querySelectorAll('.notification-item-container').length;

        if (notificationNumber) {
            notificationNumber.textContent = count;
        }

        let dot = notificationDropdownButton.querySelector('.notifications-symbol');
        if (count > 0 && !dot) {
            dot = document.createElement('div');
            dot.className = 'notifications-symbol';
            notificationDropdownButton.appendChild(dot);
        }

        if (count === 0 && dot) {
            dot.remove();
        }
    }


     const connection = new signalR.HubConnectionBuilder()
        .withUrl("/notificationHub")
        .build()

        connection.on("ReceiveNotification", (notification) => {
            const notifications = document.querySelector('.notifications')

            const item = document.createElement('div')
            item.className = "notification-item-container"
            item.setAttribute('data-id', notification.id)
            item.innerHTML =
            `
            <img class="image" src="${notification.image}" />
            <div class="message">${notification.message}</div>
            <div class="time" data-created="${new Date(notification.createDate).toISOString()}">${notification.createDate}</div>
            <button class="btn btn-close" onclick="dismissNotification('${notification.id}')"></button>
            `
            notifications.insertBefore(item, notifications.firstChild)
            updateRelativeTimes()
            updateNotificationCount()
        })


        connection.start().catch(error => console.error(error))

</script>

Presentation/Views/Shared/Partials/_ProfileOptionsMenu.cshtml
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
    var roleName = User.FindFirstValue(ClaimTypes.Role) ?? "";
    var displayName = await userService.GetDisplayNameAsync(userId);
    var profileResult = await userService.GetUserByIdAsync(userId);
    var profile = profileResult.Result;
}

<div class="profile-menu-container">
    @if (!string.IsNullOrEmpty(profile!.ImageUrl))
    {
        <img id="profileAvatar" data-type="dropdown" data-target="#profileDropdown" class="profile-avatar" src="~/Images/Profiles/@profile!.ImageUrl" alt="@displayName" />
    }
    else
    {
        <img id="profileAvatar" data-type="dropdown" data-target="#profileDropdown" class="profile-avatar" src="~/Images/Avatars/avatar.svg" alt="Avatar Image" />
    }

</div>

<div id="profileDropdown" class="profile-dropdown">
    <div class="profile-info">
        @if (!string.IsNullOrEmpty(profile!.ImageUrl))
        {
            <img class="profile-avatar-mini" src="~/Images/Profiles/@profile!.ImageUrl" alt="@displayName" />
        }
        else
        {
            <img class="profile-avatar-mini" src="~/Images/Profiles/avatar.svg" alt="Avatar Image" />
        }
        <span class="profile-name">@displayName</span>
    </div>

    <div class="profile-action">
        <div class="label">
            <i class="bi bi-gear-fill"></i>
            <span>Dark Mode</span>
        </div>
        <label class="switch">
            <input type="checkbox" id="darkModeToggle" data-type="toggle" data-func="darkmode"/>
            <span class="slider"></span>
        </label>
    </div>

    <div class="divider"></div>

    <a class="profile-logout" asp-controller="Auth" asp-action="SignOut">
        <i class="bi bi-box-arrow-right"></i>
        <span>Sign out</span>
    </a>
</div>

Presentation/Views/Shared/Partials/_SearchBar.cshtml
<div class="searchbar-container">
    <form>
        <div class="search-group">
            <button class="search-btn" type="submit"><i class="bi bi-search"></i></button>
            <input type="text" class="search" placeholder="Search..." />
        </div>
    </form>
</div>

Presentation/Views/Shared/Partials/_SettingsMenu.cshtml
<div class="settings-menu-container">
    <div id="settingsIcon" data-type="dropdown" data-target="#settingsDropdown" class="settings-icon"><i class="bi bi-gear-fill"></i></div>
</div>

<div id="settingsDropdown" class="settings-dropdown">
    <p>Settings</p>
</div>

Presentation/Views/Shared/Partials/_TopMenu.cshtml
<div class="top-menu">
    <partial name="Partials/_notificationsMenu"/>
    <partial name="Partials/_SettingsMenu" />
    <div class="top-menu-divider"></div>
    <partial name="Partials/_ProfileOptionsMenu" />
    <button type="button" data-type="menu" data-target="#sidebar" class="btn-menu"></button>
</div>